Feature: Validate various scenarios related NBC Crew Request

  #Background:
  #Given user opens producer dashboard application
  @api2024
  Scenario Outline: Create a NBC News Crew Request
    Given user set up base uri
    And user set up headers
      | Content-Type | application/Json |
      | messageid    | sdsddsd12        |
    When user invokes "Create_NBC_Crew_Request" service to create new request
      """
      {
      "crewRequestID": "",
      "crewType": "<Crew Type>",
      "division": "",
      "title": "R, Jeevanandham 206711859",
      "requester": "R, Jeevanandham",
      "cellPhone": "",
      "deskNumber": "",
      "requestorKey": "jeevanandham.r@nbcuni.com",
      "requesters": [
      {
      "displayName": "R, Jeevanandham",
      "emailId": "jeevanandham.r@nbcuni.com",
      "jobTitle": "QA Engineer",
      "ssoId": 206711859,
      "workPhone": ""
      }
      ],
      "ccEmailKey": "jeevanandham.r@nbcuni.com",
      "isThereAnOnsiteProducer": "no",
      "producerSameAsRequestor": "Yes",
      "isRequestorProducer": "Yes",
      "producer": "R, Jeevanandham",
      "fieldContactName": "R, Jeevanandham",
      "producerCellNumber": "1212121212",
      "producerDeskNumber": "",
      "approver": "Solai, Saravanan ",
      "seniorProducerKey": "saravanan.Solai@nbcuni.com",
      "assignmentSlug": "test",
      "attachEditRequestID": "",
      "audioNeed": "1-2 Audio Sources",
      "bureauLocation": "LOS ANGELES BUREAU",
      "crewAddress": "100 Universal City Plaza, Building 1126",
      "addressNotes": "",
      "crewCity": "Universal City",
      "crewState": "CA",
      "crewRegion": "WEST",
      "zip": "91608",
      "country": "United States of America",
      "locationNotes": "",
      "startDate": 1707994800,
      "endDate": 1710526500,
      "meetTime": "12:00 AM",
      "rollTime": "03:00 AM",
      "endTime": "11:15 AM",
      "daysShoot": 30,
      "dayZone": "PT",
      "camera": 1,
      "audio": 1,
      "utilities": 0,
      "resourceReason": "",
      "resourceDescription": "",
      "productionType": "BREAKING NEWS",
      "transmissionType": "AFFILIATE/STUDIO",
      "acquisitionSpecs": "Broadcast/Live Standard(FHD 1920x1080/60i/No LOG)",
      "acquisitionOther": "",
      "acquisitionLutText": "",
      "shootDescription": "test",
      "shootStatus": "Firm",
      "shootType": "",
      "colorSpace": "",
      "specialConditions": "High profile guest",
      "iPadPrompter": "no",
      "droneShoot": "No",
      "usingCam": "No",
      "specialGear": "no",
      "gearNotes": "",
      "crewAttachments": [],
      "camUpdated": true,
      "editRequestIdUpdated": true,
      "riskCategory": "Standard",
      "riskOther": "",
      "riskSafetyArrangement": "",
      "riskApprover": "",
      "riskApproverKey": "",
      "showunit": [
      {
      "id": 1670906313318,
      "showunittitle": "Exec_test_1",
      "budgetCode": "88393"
      }
      ],
      "talent": [
      {
      "name": "<talent>"
      }
      ],
      "storyName": "Test story websocket testing - edited twice",
      "storySlugID": 1707795138651,
      "requesterNotes": [],
      "revisionLog": [],
      "revisionNotes": [],
      "selectedResources": 2,
      "suggestedResources": 2,
      "labourCost": "$2,000",
      "gearCost": "$1,500",
      "suggestedCamera": 1,
      "suggestedAudio": 1,
      "suggestedUtilities": 0,
      "estimatedCost": "$3,500",
      "overrideApproval": 0,
      "requestApproverkey": "",
      "comments": "",
      "crewDeskNotes": "",
      "riskAircraft": "no",
      "riskEandD": "no",
      "riskWater": "no",
      "riskRoad": "no",
      "riskHMI": "no",
      "riskLive": "no",
      "riskLongWorking": "no",
      "riskRiot": "no",
      "riskWeather": "no",
      "riskStructure": "no",
      "riskWarZone": "no",
      "riskHeights": "no",
      "riskNone": "no",
      "travelStartDate": 1707980400,
      "travelEndDate": 1710530100,
      "resource": [],
      "requestStatus": "NEW",
      "mediaFormat": "",
      "videoSpecs": "",
      "primaryCameraType": "",
      "crewStatus": "Save",
      "deleted": false,
      "unifiedRequestId": "",
      "producerKey": "jeevanandham.r@nbcuni.com",
      "producerName": "R, Jeevanandham",
      "requestComplete": true,
      "requestorName": "R, Jeevanandham",
      "requestorEmail": "jeevanandham.r@nbcuni.com",
      "requestorContact": "",
      "seniorProducer": "Solai, Saravanan ",
      "slug": "test"
      }
      """
    Then validate the status code "201"
    Given user set up base uri
    And user set up headers
      | Content-Type | application/Json |
      | messageid    | sdsddsd12        |
    And user invokes "Common_Search_Request" service to search the request
      """
      {
      "filter": {
      "id": "*"
      },
      "status": [
      "NEW",
      "MODIFIED",
      "WORKING",
      "REVISED",
      "Efforting",
      "ROFR",
      "Booked",
      "FULFILLED",
      "COMPLETED",
      "CONFIRM CANCELLATION",
      "IN PROGRESS",
      "CANCELLED",
      "Acknowledged",
      "Ready For Pick Up",
      "Extended"
      ],
      "requestType": [
      "General Crew Request",
      "Single Camera Live Shot",
      "Extended or Bridge Crew and Facilities",
      "All Studio Production Request",
      "Animals on Premises",
      "FireArms Request",
      "CNBC Production Request",
      "Telemundo Crew",
      "CNBC Crew",
      "Digital Journalist",
      "Breaking News",
      "Bureau Camera",
      "News Gear",
      "CNBC Gear",
      "Edit Request",
      "Long Form Edit Request",
      "File Ingest",
      "Feed Out",
      "MTD",
      "Edit Self Reporting"
      ],
      "requestId": "",
      "daterange": {},
      "showUnit": [],
      "slugValue": "",
      "search": "CR2024766661",
      "start": 1,
      "count": 20,
      "sortField": "created",
      "sortOrder": "descending",
      "loginName": ""
      }
      """
    Then validate the status code "200"
    Then validate "request id" in the response "results[0].id"
    Then user invokes "Update_NBC_Crew_Request" service to Revise the request
      """
      {
      "assignmentSlug": "test",
      "storyName": "Test story websocket testing - edited twice",
      "storySlugID": "1707795138651",
      "division": "",
      "requesters": [
      {
        "displayName": "R, Jeevanandham",
        "thumbnailUrl": null,
        "userId": null,
        "jobTitle": "QA Engineer",
        "ssoId": "206711859",
        "emailId": "jeevanandham.r@nbcuni.com",
        "workPhone": ""
      }
      ],
      "requester": "R, Jeevanandham",
      "title": "R, Jeevanandham 206711859",
      "cellPhone": "",
      "talent": [
      {
        "id": 0,
        "name": "<talent>"
      }
      ],
      "producerSameAsRequestor": "Yes",
      "producer": "R, Jeevanandham",
      "fieldContactName": "R, Jeevanandham",
      "producerCellNumber": "1212121212",
      "producerKey": "jeevanandham.r@nbcuni.com",
      "seniorProducerKey": "saravanan.Solai@nbcuni.com",
      "approvedBySenior": null,
      "isThereAnOnsiteProducer": "no",
      "approver": "Solai, Saravanan ",
      "showunit": [
      {
        "id": 1670906313318,
        "showunittitle": "Exec_test_1",
        "budgetCode": "88393"
      }
      ],
      "productionType": "BREAKING NEWS",
      "shootStatus": "Firm",
      "shootDescription": "<Shoot Description>",
      "shootType": "",
      "attachEditRequestID": "",
      "audioNeed": "1-2 Audio Sources",
      "specialConditions": "High profile guest",
      "transmissionType": "AFFILIATE/STUDIO",
      "acquisitionSpecs": "Broadcast/Live Standard(FHD 1920x1080/60i/No LOG)",
      "acquisitionOther": "",
      "acquisitionLutText": "",
      "specialGear": "no",
      "gearNotes": "",
      "droneShoot": "No",
      "usingCam": "No",
      "colorSpace": "",
      "iPadPrompter": "no",
      "crewAttachments": [],
      "crewRegion": "WEST",
      "bureauLocation": "LOS ANGELES BUREAU",
      "crewAddress": "100 Universal City Plaza, Building 1126",
      "addressNotes": "",
      "crewCity": "Universal City",
      "crewState": "CA",
      "zip": "91608",
      "country": "United States of America",
      "locationNotes": "",
      "riskCategory": "Standard",
      "riskAircraft": "no",
      "riskApprover": "",
      "riskEandD": "no",
      "riskWater": "no",
      "riskRiot": "no",
      "riskWeather": "no",
      "riskWarZone": "no",
      "riskRoad": "no",
      "riskHMI": "no",
      "riskLive": "no",
      "riskLongWorking": "no",
      "riskNone": "no",
      "riskStructure": "no",
      "riskHeights": "no",
      "riskOther": "",
      "riskSafetyArrangement": "",
      "startDate": 1707994800,
      "endDate": 1710526500,
      "daysShoot": 30,
      "dayZone": "PT",
      "meetTime": "12:00 AM",
      "endTime": "11:15 AM",
      "rollTime": "03:00 AM",
      "primaryCameraType": "",
      "mediaFormat": "",
      "videoSpecs": "",
      "comments": "",
      "resourceDescription": "",
      "resourceReason": "",
      "revisionNotes": [
      {
        "comments": "New Crew Request is submitted",
        "revisedBy": "R, Jeevanandham",
        "revisedDate": 1707976910,
        "state": "NEW"
      }
      ],
      "revisionLog": [],
      "requesterNotes": [],
      "resource": [],
      "ccEmailKey": "jeevanandham.r@nbcuni.com",
      "estimatedCost": "$3,500",
      "gearCost": "$1,500",
      "labourCost": "$2,000",
      "deskNumber": "",
      "camera": 1,
      "audio": 1,
      "utilities": 0,
      "stormResource": null,
      "suggestedCamera": 1,
      "suggestedAudio": 1,
      "suggestedUtilities": 0,
      "additionalCamera": 0,
      "additionalAudio": 0,
      "additionalUtilities": 0,
      "suggestedResources": 2,
      "selectedResources": 2,
      "crewResourceDetails": null,
      "overrideApproval": 0,
      "legacyReq": false,
      "requestComplete": true,
      "travelStartDate": 1707980400,
      "travelEndDate": 1710530100,
      "crewRequestID": "CR2024766661",
      "requestStatus": "NEW",
      "crewType": "General Crew Request",
      "crewStatus": "Save",
      "deleted": false,
      "created": 1707976910,
      "modified": 1707976910,
      "modifiedBy": "R, Jeevanandham",
      "unifiedRequestId": "",
      "stormIntegration": false,
      "stormID": 0,
      "loggedInUser": "R, Jeevanandham",
      "loggedInSSO": "206711859",
      "cancelled": false,
      "budgetCodeChanges": [],
      "approval": null,
      "producerDeskNumber": "",
      "attachments": null,
      "sharepointID": 0,
      "maxEstimatedCost": 0,
      "assignedResources": 0,
      "authorId": null,
      "editorId": null,
      "travelExpenses": null,
      "resourcesKey": null,
      "requestApproverkey": "",
      "crewDeskNotes": "",
      "indoorShoot": null,
      "ccEmail": null,
      "additionalCCfield": null,
      "crewDeskFile": null,
      "studioType": null,
      "client": null,
      "camUpdated": true,
      "editRequestIdUpdated": true,
      "slug": "test",
      "isRequestorProducer": "Yes",
      "producerName": "R, Jeevanandham",
      "seniorProducer": "Solai, Saravanan ",
      "riskApproverKey": "",
      "airDate": 0,
      "airDateTBD": "No",
      "airTime": "",
      "airTimeFlexible": "No",
      "requestorName": "R, Jeevanandham"
      }
      """
    Then validate the status code "200"

    Examples: 
      | Crew Type            | Talent      | Shoot Description |
      | General Crew Request | TestPerson1 | Test Description  |
      | General Crew Request | TestPerson2 | Test Description  |
      | General Crew Request | TestPerson3 | Test Description  |
